//client <---> scene

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: cs.proto

package cs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ID int32

const (
	ID_ID_Zero         ID = 0
	ID_ID_S2C_OpObject ID = 1000
	// 角色基本信息
	ID_ID_C2S_GetUser ID = 10001
	ID_ID_S2C_GetUser ID = 10002
	// 出生
	ID_ID_C2S_BORN ID = 10101
	ID_ID_S2C_BORN ID = 10102
	// 死亡
	ID_ID_C2S_DEAD ID = 10103
	ID_ID_S2C_DEAD ID = 10104
	// ---------------角色交互
	// 移动
	ID_ID_C2S_MOVE ID = 11001
	ID_ID_S2C_MOVE ID = 11002
	// 砍树
	ID_ID_C2S_CUT_DOWN_TREE ID = 11011
	ID_ID_S2C_CUT_DOWN_TREE ID = 11012
	// 被砍伐
	ID_ID_C2S_BE_CUT_DOWN_TREE ID = 11013
	ID_ID_S2C_BE_CUT_DOWN_TREE ID = 11014
	// 睡觉
	ID_ID_C2S_SLEEP ID = 11021
	ID_ID_S2C_SLEEP ID = 11022
	// 吃东西
	ID_ID_C2S_EAT ID = 11031
	ID_ID_S2C_EAT ID = 11032
	// 拾取
	ID_ID_C2S_PICK_UP ID = 11041
	ID_ID_S2C_PICK_UP ID = 11042
	// 生长
	ID_ID_C2S_GROWTH ID = 11051
	ID_ID_S2C_GROWTH ID = 11052
	// 合成工具
	ID_ID_C2S_COMPOSE_TOOLS ID = 11061
	ID_ID_S2C_COMPOSE_TOOLS ID = 11062
	// 大消息
	ID_ID_S2C_BASE_TOOLS_HUGE_MSG_PACK     ID = 99998
	ID_ID_S2C_BASE_TOOLS_HUGE_MSG_SUB_PACK ID = 99999
)

// Enum value maps for ID.
var (
	ID_name = map[int32]string{
		0:     "ID_Zero",
		1000:  "ID_S2C_OpObject",
		10001: "ID_C2S_GetUser",
		10002: "ID_S2C_GetUser",
		10101: "ID_C2S_BORN",
		10102: "ID_S2C_BORN",
		10103: "ID_C2S_DEAD",
		10104: "ID_S2C_DEAD",
		11001: "ID_C2S_MOVE",
		11002: "ID_S2C_MOVE",
		11011: "ID_C2S_CUT_DOWN_TREE",
		11012: "ID_S2C_CUT_DOWN_TREE",
		11013: "ID_C2S_BE_CUT_DOWN_TREE",
		11014: "ID_S2C_BE_CUT_DOWN_TREE",
		11021: "ID_C2S_SLEEP",
		11022: "ID_S2C_SLEEP",
		11031: "ID_C2S_EAT",
		11032: "ID_S2C_EAT",
		11041: "ID_C2S_PICK_UP",
		11042: "ID_S2C_PICK_UP",
		11051: "ID_C2S_GROWTH",
		11052: "ID_S2C_GROWTH",
		11061: "ID_C2S_COMPOSE_TOOLS",
		11062: "ID_S2C_COMPOSE_TOOLS",
		99998: "ID_S2C_BASE_TOOLS_HUGE_MSG_PACK",
		99999: "ID_S2C_BASE_TOOLS_HUGE_MSG_SUB_PACK",
	}
	ID_value = map[string]int32{
		"ID_Zero":                             0,
		"ID_S2C_OpObject":                     1000,
		"ID_C2S_GetUser":                      10001,
		"ID_S2C_GetUser":                      10002,
		"ID_C2S_BORN":                         10101,
		"ID_S2C_BORN":                         10102,
		"ID_C2S_DEAD":                         10103,
		"ID_S2C_DEAD":                         10104,
		"ID_C2S_MOVE":                         11001,
		"ID_S2C_MOVE":                         11002,
		"ID_C2S_CUT_DOWN_TREE":                11011,
		"ID_S2C_CUT_DOWN_TREE":                11012,
		"ID_C2S_BE_CUT_DOWN_TREE":             11013,
		"ID_S2C_BE_CUT_DOWN_TREE":             11014,
		"ID_C2S_SLEEP":                        11021,
		"ID_S2C_SLEEP":                        11022,
		"ID_C2S_EAT":                          11031,
		"ID_S2C_EAT":                          11032,
		"ID_C2S_PICK_UP":                      11041,
		"ID_S2C_PICK_UP":                      11042,
		"ID_C2S_GROWTH":                       11051,
		"ID_S2C_GROWTH":                       11052,
		"ID_C2S_COMPOSE_TOOLS":                11061,
		"ID_S2C_COMPOSE_TOOLS":                11062,
		"ID_S2C_BASE_TOOLS_HUGE_MSG_PACK":     99998,
		"ID_S2C_BASE_TOOLS_HUGE_MSG_SUB_PACK": 99999,
	}
)

func (x ID) Enum() *ID {
	p := new(ID)
	*p = x
	return p
}

func (x ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ID) Descriptor() protoreflect.EnumDescriptor {
	return file_cs_proto_enumTypes[0].Descriptor()
}

func (ID) Type() protoreflect.EnumType {
	return &file_cs_proto_enumTypes[0]
}

func (x ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ID.Descriptor instead.
func (ID) EnumDescriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{0}
}

type Zero struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Zero) Reset() {
	*x = Zero{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Zero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zero) ProtoMessage() {}

func (x *Zero) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zero.ProtoReflect.Descriptor instead.
func (*Zero) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OpUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Insert []*User `protobuf:"bytes,1,rep,name=insert,proto3" json:"insert,omitempty"`
	Update []*User `protobuf:"bytes,2,rep,name=update,proto3" json:"update,omitempty"`
	Delete []*User `protobuf:"bytes,3,rep,name=delete,proto3" json:"delete,omitempty"`
}

func (x *OpUser) Reset() {
	*x = OpUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpUser) ProtoMessage() {}

func (x *OpUser) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpUser.ProtoReflect.Descriptor instead.
func (*OpUser) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{2}
}

func (x *OpUser) GetInsert() []*User {
	if x != nil {
		return x.Insert
	}
	return nil
}

func (x *OpUser) GetUpdate() []*User {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *OpUser) GetDelete() []*User {
	if x != nil {
		return x.Delete
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 唯一id,=0则无唯一
	Type  uint32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Value uint32 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Size  uint32 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{3}
}

func (x *Item) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Item) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Item) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type S2C_OpObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpUser *OpUser `protobuf:"bytes,1,opt,name=opUser,proto3" json:"opUser,omitempty"`
}

func (x *S2C_OpObject) Reset() {
	*x = S2C_OpObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_OpObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_OpObject) ProtoMessage() {}

func (x *S2C_OpObject) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_OpObject.ProtoReflect.Descriptor instead.
func (*S2C_OpObject) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{4}
}

func (x *S2C_OpObject) GetOpUser() *OpUser {
	if x != nil {
		return x.OpUser
	}
	return nil
}

type C2S_GetUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret uint32 `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Id  uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *C2S_GetUser) Reset() {
	*x = C2S_GetUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_GetUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_GetUser) ProtoMessage() {}

func (x *C2S_GetUser) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_GetUser.ProtoReflect.Descriptor instead.
func (*C2S_GetUser) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{5}
}

func (x *C2S_GetUser) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *C2S_GetUser) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type S2C_GetUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret  uint32 `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	User *User  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *S2C_GetUser) Reset() {
	*x = S2C_GetUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_GetUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_GetUser) ProtoMessage() {}

func (x *S2C_GetUser) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_GetUser.ProtoReflect.Descriptor instead.
func (*S2C_GetUser) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{6}
}

func (x *S2C_GetUser) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *S2C_GetUser) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 出生
type C2S_BORN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    uint32 `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *C2S_BORN) Reset() {
	*x = C2S_BORN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_BORN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_BORN) ProtoMessage() {}

func (x *C2S_BORN) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_BORN.ProtoReflect.Descriptor instead.
func (*C2S_BORN) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{7}
}

func (x *C2S_BORN) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *C2S_BORN) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type S2C_BORN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret  uint32 `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	User *User  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *S2C_BORN) Reset() {
	*x = S2C_BORN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_BORN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_BORN) ProtoMessage() {}

func (x *S2C_BORN) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_BORN.ProtoReflect.Descriptor instead.
func (*S2C_BORN) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{8}
}

func (x *S2C_BORN) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *S2C_BORN) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 死亡
type C2S_DEAD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    uint32 `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *C2S_DEAD) Reset() {
	*x = C2S_DEAD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_DEAD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_DEAD) ProtoMessage() {}

func (x *C2S_DEAD) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_DEAD.ProtoReflect.Descriptor instead.
func (*C2S_DEAD) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{9}
}

func (x *C2S_DEAD) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *C2S_DEAD) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type S2C_DEAD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    uint32 `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *S2C_DEAD) Reset() {
	*x = S2C_DEAD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_DEAD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_DEAD) ProtoMessage() {}

func (x *S2C_DEAD) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_DEAD.ProtoReflect.Descriptor instead.
func (*S2C_DEAD) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{10}
}

func (x *S2C_DEAD) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *S2C_DEAD) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type C2S_MOVE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    uint32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId uint64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	X      float32 `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y      float32 `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *C2S_MOVE) Reset() {
	*x = C2S_MOVE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_MOVE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_MOVE) ProtoMessage() {}

func (x *C2S_MOVE) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_MOVE.ProtoReflect.Descriptor instead.
func (*C2S_MOVE) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{11}
}

func (x *C2S_MOVE) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *C2S_MOVE) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *C2S_MOVE) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *C2S_MOVE) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type S2C_MOVE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    uint32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId uint64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	X      float32 `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y      float32 `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *S2C_MOVE) Reset() {
	*x = S2C_MOVE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_MOVE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_MOVE) ProtoMessage() {}

func (x *S2C_MOVE) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_MOVE.ProtoReflect.Descriptor instead.
func (*S2C_MOVE) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{12}
}

func (x *S2C_MOVE) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *S2C_MOVE) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *S2C_MOVE) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *S2C_MOVE) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type C2S_CUT_DOWN_TREE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    uint32 `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	TreeId uint64 `protobuf:"varint,3,opt,name=treeId,proto3" json:"treeId,omitempty"`
}

func (x *C2S_CUT_DOWN_TREE) Reset() {
	*x = C2S_CUT_DOWN_TREE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_CUT_DOWN_TREE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_CUT_DOWN_TREE) ProtoMessage() {}

func (x *C2S_CUT_DOWN_TREE) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_CUT_DOWN_TREE.ProtoReflect.Descriptor instead.
func (*C2S_CUT_DOWN_TREE) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{13}
}

func (x *C2S_CUT_DOWN_TREE) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *C2S_CUT_DOWN_TREE) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *C2S_CUT_DOWN_TREE) GetTreeId() uint64 {
	if x != nil {
		return x.TreeId
	}
	return 0
}

type S2C_CUT_DOWN_TREE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    uint32 `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	TreeId uint64 `protobuf:"varint,3,opt,name=treeId,proto3" json:"treeId,omitempty"`
}

func (x *S2C_CUT_DOWN_TREE) Reset() {
	*x = S2C_CUT_DOWN_TREE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_CUT_DOWN_TREE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_CUT_DOWN_TREE) ProtoMessage() {}

func (x *S2C_CUT_DOWN_TREE) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_CUT_DOWN_TREE.ProtoReflect.Descriptor instead.
func (*S2C_CUT_DOWN_TREE) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{14}
}

func (x *S2C_CUT_DOWN_TREE) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *S2C_CUT_DOWN_TREE) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *S2C_CUT_DOWN_TREE) GetTreeId() uint64 {
	if x != nil {
		return x.TreeId
	}
	return 0
}

type C2S_BE_CUT_DOWN_TREE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    uint32 `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	TreeId uint64 `protobuf:"varint,3,opt,name=treeId,proto3" json:"treeId,omitempty"`
}

func (x *C2S_BE_CUT_DOWN_TREE) Reset() {
	*x = C2S_BE_CUT_DOWN_TREE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_BE_CUT_DOWN_TREE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_BE_CUT_DOWN_TREE) ProtoMessage() {}

func (x *C2S_BE_CUT_DOWN_TREE) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_BE_CUT_DOWN_TREE.ProtoReflect.Descriptor instead.
func (*C2S_BE_CUT_DOWN_TREE) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{15}
}

func (x *C2S_BE_CUT_DOWN_TREE) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *C2S_BE_CUT_DOWN_TREE) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *C2S_BE_CUT_DOWN_TREE) GetTreeId() uint64 {
	if x != nil {
		return x.TreeId
	}
	return 0
}

type S2C_BE_CUT_DOWN_TREE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    uint32 `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	TreeId uint64 `protobuf:"varint,3,opt,name=treeId,proto3" json:"treeId,omitempty"`
}

func (x *S2C_BE_CUT_DOWN_TREE) Reset() {
	*x = S2C_BE_CUT_DOWN_TREE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_BE_CUT_DOWN_TREE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_BE_CUT_DOWN_TREE) ProtoMessage() {}

func (x *S2C_BE_CUT_DOWN_TREE) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_BE_CUT_DOWN_TREE.ProtoReflect.Descriptor instead.
func (*S2C_BE_CUT_DOWN_TREE) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{16}
}

func (x *S2C_BE_CUT_DOWN_TREE) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *S2C_BE_CUT_DOWN_TREE) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *S2C_BE_CUT_DOWN_TREE) GetTreeId() uint64 {
	if x != nil {
		return x.TreeId
	}
	return 0
}

type C2S_SLEEP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    uint32 `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *C2S_SLEEP) Reset() {
	*x = C2S_SLEEP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_SLEEP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_SLEEP) ProtoMessage() {}

func (x *C2S_SLEEP) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_SLEEP.ProtoReflect.Descriptor instead.
func (*C2S_SLEEP) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{17}
}

func (x *C2S_SLEEP) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *C2S_SLEEP) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type S2C_SLEEP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    uint32 `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *S2C_SLEEP) Reset() {
	*x = S2C_SLEEP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_SLEEP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_SLEEP) ProtoMessage() {}

func (x *S2C_SLEEP) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_SLEEP.ProtoReflect.Descriptor instead.
func (*S2C_SLEEP) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{18}
}

func (x *S2C_SLEEP) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *S2C_SLEEP) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type C2S_EAT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    uint32 `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *C2S_EAT) Reset() {
	*x = C2S_EAT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_EAT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_EAT) ProtoMessage() {}

func (x *C2S_EAT) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_EAT.ProtoReflect.Descriptor instead.
func (*C2S_EAT) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{19}
}

func (x *C2S_EAT) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *C2S_EAT) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type S2C_EAT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    uint32 `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *S2C_EAT) Reset() {
	*x = S2C_EAT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_EAT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_EAT) ProtoMessage() {}

func (x *S2C_EAT) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_EAT.ProtoReflect.Descriptor instead.
func (*S2C_EAT) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{20}
}

func (x *S2C_EAT) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *S2C_EAT) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type C2S_PICK_UP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret      uint32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId   uint64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ItemList []*Item `protobuf:"bytes,3,rep,name=itemList,proto3" json:"itemList,omitempty"`
}

func (x *C2S_PICK_UP) Reset() {
	*x = C2S_PICK_UP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_PICK_UP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_PICK_UP) ProtoMessage() {}

func (x *C2S_PICK_UP) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_PICK_UP.ProtoReflect.Descriptor instead.
func (*C2S_PICK_UP) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{21}
}

func (x *C2S_PICK_UP) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *C2S_PICK_UP) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *C2S_PICK_UP) GetItemList() []*Item {
	if x != nil {
		return x.ItemList
	}
	return nil
}

type S2C_PICK_UP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret      uint32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId   uint64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ItemList []*Item `protobuf:"bytes,3,rep,name=itemList,proto3" json:"itemList,omitempty"`
}

func (x *S2C_PICK_UP) Reset() {
	*x = S2C_PICK_UP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_PICK_UP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_PICK_UP) ProtoMessage() {}

func (x *S2C_PICK_UP) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_PICK_UP.ProtoReflect.Descriptor instead.
func (*S2C_PICK_UP) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{22}
}

func (x *S2C_PICK_UP) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *S2C_PICK_UP) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *S2C_PICK_UP) GetItemList() []*Item {
	if x != nil {
		return x.ItemList
	}
	return nil
}

type C2S_GROWTH struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    uint32 `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *C2S_GROWTH) Reset() {
	*x = C2S_GROWTH{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_GROWTH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_GROWTH) ProtoMessage() {}

func (x *C2S_GROWTH) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_GROWTH.ProtoReflect.Descriptor instead.
func (*C2S_GROWTH) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{23}
}

func (x *C2S_GROWTH) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *C2S_GROWTH) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type S2C_GROWTH struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    uint32 `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *S2C_GROWTH) Reset() {
	*x = S2C_GROWTH{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_GROWTH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_GROWTH) ProtoMessage() {}

func (x *S2C_GROWTH) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_GROWTH.ProtoReflect.Descriptor instead.
func (*S2C_GROWTH) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{24}
}

func (x *S2C_GROWTH) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *S2C_GROWTH) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type C2S_COMPOSE_TOOLS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret        uint32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId     uint64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	NeedItem   []*Item `protobuf:"bytes,3,rep,name=needItem,proto3" json:"needItem,omitempty"`
	ResultItem []*Item `protobuf:"bytes,4,rep,name=resultItem,proto3" json:"resultItem,omitempty"`
}

func (x *C2S_COMPOSE_TOOLS) Reset() {
	*x = C2S_COMPOSE_TOOLS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_COMPOSE_TOOLS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_COMPOSE_TOOLS) ProtoMessage() {}

func (x *C2S_COMPOSE_TOOLS) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_COMPOSE_TOOLS.ProtoReflect.Descriptor instead.
func (*C2S_COMPOSE_TOOLS) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{25}
}

func (x *C2S_COMPOSE_TOOLS) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *C2S_COMPOSE_TOOLS) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *C2S_COMPOSE_TOOLS) GetNeedItem() []*Item {
	if x != nil {
		return x.NeedItem
	}
	return nil
}

func (x *C2S_COMPOSE_TOOLS) GetResultItem() []*Item {
	if x != nil {
		return x.ResultItem
	}
	return nil
}

type S2C_COMPOSE_TOOLS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret        uint32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserId     uint64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	NeedItem   []*Item `protobuf:"bytes,3,rep,name=needItem,proto3" json:"needItem,omitempty"`
	ResultItem []*Item `protobuf:"bytes,4,rep,name=resultItem,proto3" json:"resultItem,omitempty"`
}

func (x *S2C_COMPOSE_TOOLS) Reset() {
	*x = S2C_COMPOSE_TOOLS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_COMPOSE_TOOLS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_COMPOSE_TOOLS) ProtoMessage() {}

func (x *S2C_COMPOSE_TOOLS) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_COMPOSE_TOOLS.ProtoReflect.Descriptor instead.
func (*S2C_COMPOSE_TOOLS) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{26}
}

func (x *S2C_COMPOSE_TOOLS) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *S2C_COMPOSE_TOOLS) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *S2C_COMPOSE_TOOLS) GetNeedItem() []*Item {
	if x != nil {
		return x.NeedItem
	}
	return nil
}

func (x *S2C_COMPOSE_TOOLS) GetResultItem() []*Item {
	if x != nil {
		return x.ResultItem
	}
	return nil
}

var File_cs_proto protoreflect.FileDescriptor

var file_cs_proto_rawDesc = []byte{
	0x0a, 0x08, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x63, 0x73, 0x22, 0x06,
	0x0a, 0x04, 0x5a, 0x65, 0x72, 0x6f, 0x22, 0x16, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6e,
	0x0a, 0x06, 0x4f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x06, 0x69, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63, 0x73, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x06, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x06, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63, 0x73, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x06,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63,
	0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x22, 0x54,
	0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x22, 0x32, 0x0a, 0x0c, 0x53, 0x32, 0x43, 0x5f, 0x4f, 0x70, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x22, 0x0a, 0x06, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x73, 0x2e, 0x4f, 0x70, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x06, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x22, 0x2f, 0x0a, 0x0b, 0x43, 0x32, 0x53, 0x5f,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x0b, 0x53, 0x32, 0x43,
	0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63, 0x73, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x34, 0x0a, 0x08, 0x43, 0x32, 0x53, 0x5f,
	0x42, 0x4f, 0x52, 0x4e, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3a,
	0x0a, 0x08, 0x53, 0x32, 0x43, 0x5f, 0x42, 0x4f, 0x52, 0x4e, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63, 0x73, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x34, 0x0a, 0x08, 0x43, 0x32,
	0x53, 0x5f, 0x44, 0x45, 0x41, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x34, 0x0a, 0x08, 0x53, 0x32, 0x43, 0x5f, 0x44, 0x45, 0x41, 0x44, 0x12, 0x10, 0x0a, 0x03,
	0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x08, 0x43, 0x32, 0x53, 0x5f, 0x4d, 0x4f,
	0x56, 0x45, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x50, 0x0a, 0x08, 0x53, 0x32, 0x43, 0x5f,
	0x4d, 0x4f, 0x56, 0x45, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x55, 0x0a, 0x11, 0x43, 0x32,
	0x53, 0x5f, 0x43, 0x55, 0x54, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x5f, 0x54, 0x52, 0x45, 0x45, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x72, 0x65,
	0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x72, 0x65, 0x65, 0x49,
	0x64, 0x22, 0x55, 0x0a, 0x11, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x55, 0x54, 0x5f, 0x44, 0x4f, 0x57,
	0x4e, 0x5f, 0x54, 0x52, 0x45, 0x45, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x72, 0x65, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x74, 0x72, 0x65, 0x65, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x14, 0x43, 0x32, 0x53, 0x5f,
	0x42, 0x45, 0x5f, 0x43, 0x55, 0x54, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x5f, 0x54, 0x52, 0x45, 0x45,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72,
	0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x72,
	0x65, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x72, 0x65, 0x65,
	0x49, 0x64, 0x22, 0x58, 0x0a, 0x14, 0x53, 0x32, 0x43, 0x5f, 0x42, 0x45, 0x5f, 0x43, 0x55, 0x54,
	0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x5f, 0x54, 0x52, 0x45, 0x45, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x72, 0x65, 0x65, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x72, 0x65, 0x65, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x09,
	0x43, 0x32, 0x53, 0x5f, 0x53, 0x4c, 0x45, 0x45, 0x50, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x09, 0x53, 0x32, 0x43, 0x5f, 0x53, 0x4c, 0x45, 0x45, 0x50,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72,
	0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x07, 0x43, 0x32,
	0x53, 0x5f, 0x45, 0x41, 0x54, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x33, 0x0a, 0x07, 0x53, 0x32, 0x43, 0x5f, 0x45, 0x41, 0x54, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x5d, 0x0a, 0x0b, 0x43, 0x32, 0x53, 0x5f, 0x50, 0x49, 0x43, 0x4b,
	0x5f, 0x55, 0x50, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a,
	0x08, 0x69, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x63, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x5d, 0x0a, 0x0b, 0x53, 0x32, 0x43, 0x5f, 0x50, 0x49, 0x43, 0x4b, 0x5f,
	0x55, 0x50, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x08,
	0x69, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x63, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x36, 0x0a, 0x0a, 0x43, 0x32, 0x53, 0x5f, 0x47, 0x52, 0x4f, 0x57, 0x54, 0x48,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72,
	0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x0a, 0x53, 0x32,
	0x43, 0x5f, 0x47, 0x52, 0x4f, 0x57, 0x54, 0x48, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x8d, 0x01, 0x0a, 0x11, 0x43, 0x32, 0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4f,
	0x53, 0x45, 0x5f, 0x54, 0x4f, 0x4f, 0x4c, 0x53, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x08, 0x6e, 0x65, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08,
	0x6e, 0x65, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x28, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63,
	0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x22, 0x8d, 0x01, 0x0a, 0x11, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4f,
	0x53, 0x45, 0x5f, 0x54, 0x4f, 0x4f, 0x4c, 0x53, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x08, 0x6e, 0x65, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08,
	0x6e, 0x65, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x28, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63,
	0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x2a, 0xd1, 0x04, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x44, 0x5f,
	0x5a, 0x65, 0x72, 0x6f, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x0f, 0x49, 0x44, 0x5f, 0x53, 0x32, 0x43,
	0x5f, 0x4f, 0x70, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x10, 0xe8, 0x07, 0x12, 0x13, 0x0a, 0x0e,
	0x49, 0x44, 0x5f, 0x43, 0x32, 0x53, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x10, 0x91,
	0x4e, 0x12, 0x13, 0x0a, 0x0e, 0x49, 0x44, 0x5f, 0x53, 0x32, 0x43, 0x5f, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x10, 0x92, 0x4e, 0x12, 0x10, 0x0a, 0x0b, 0x49, 0x44, 0x5f, 0x43, 0x32, 0x53,
	0x5f, 0x42, 0x4f, 0x52, 0x4e, 0x10, 0xf5, 0x4e, 0x12, 0x10, 0x0a, 0x0b, 0x49, 0x44, 0x5f, 0x53,
	0x32, 0x43, 0x5f, 0x42, 0x4f, 0x52, 0x4e, 0x10, 0xf6, 0x4e, 0x12, 0x10, 0x0a, 0x0b, 0x49, 0x44,
	0x5f, 0x43, 0x32, 0x53, 0x5f, 0x44, 0x45, 0x41, 0x44, 0x10, 0xf7, 0x4e, 0x12, 0x10, 0x0a, 0x0b,
	0x49, 0x44, 0x5f, 0x53, 0x32, 0x43, 0x5f, 0x44, 0x45, 0x41, 0x44, 0x10, 0xf8, 0x4e, 0x12, 0x10,
	0x0a, 0x0b, 0x49, 0x44, 0x5f, 0x43, 0x32, 0x53, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0xf9, 0x55,
	0x12, 0x10, 0x0a, 0x0b, 0x49, 0x44, 0x5f, 0x53, 0x32, 0x43, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x10,
	0xfa, 0x55, 0x12, 0x19, 0x0a, 0x14, 0x49, 0x44, 0x5f, 0x43, 0x32, 0x53, 0x5f, 0x43, 0x55, 0x54,
	0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x5f, 0x54, 0x52, 0x45, 0x45, 0x10, 0x83, 0x56, 0x12, 0x19, 0x0a,
	0x14, 0x49, 0x44, 0x5f, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x55, 0x54, 0x5f, 0x44, 0x4f, 0x57, 0x4e,
	0x5f, 0x54, 0x52, 0x45, 0x45, 0x10, 0x84, 0x56, 0x12, 0x1c, 0x0a, 0x17, 0x49, 0x44, 0x5f, 0x43,
	0x32, 0x53, 0x5f, 0x42, 0x45, 0x5f, 0x43, 0x55, 0x54, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x5f, 0x54,
	0x52, 0x45, 0x45, 0x10, 0x85, 0x56, 0x12, 0x1c, 0x0a, 0x17, 0x49, 0x44, 0x5f, 0x53, 0x32, 0x43,
	0x5f, 0x42, 0x45, 0x5f, 0x43, 0x55, 0x54, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x5f, 0x54, 0x52, 0x45,
	0x45, 0x10, 0x86, 0x56, 0x12, 0x11, 0x0a, 0x0c, 0x49, 0x44, 0x5f, 0x43, 0x32, 0x53, 0x5f, 0x53,
	0x4c, 0x45, 0x45, 0x50, 0x10, 0x8d, 0x56, 0x12, 0x11, 0x0a, 0x0c, 0x49, 0x44, 0x5f, 0x53, 0x32,
	0x43, 0x5f, 0x53, 0x4c, 0x45, 0x45, 0x50, 0x10, 0x8e, 0x56, 0x12, 0x0f, 0x0a, 0x0a, 0x49, 0x44,
	0x5f, 0x43, 0x32, 0x53, 0x5f, 0x45, 0x41, 0x54, 0x10, 0x97, 0x56, 0x12, 0x0f, 0x0a, 0x0a, 0x49,
	0x44, 0x5f, 0x53, 0x32, 0x43, 0x5f, 0x45, 0x41, 0x54, 0x10, 0x98, 0x56, 0x12, 0x13, 0x0a, 0x0e,
	0x49, 0x44, 0x5f, 0x43, 0x32, 0x53, 0x5f, 0x50, 0x49, 0x43, 0x4b, 0x5f, 0x55, 0x50, 0x10, 0xa1,
	0x56, 0x12, 0x13, 0x0a, 0x0e, 0x49, 0x44, 0x5f, 0x53, 0x32, 0x43, 0x5f, 0x50, 0x49, 0x43, 0x4b,
	0x5f, 0x55, 0x50, 0x10, 0xa2, 0x56, 0x12, 0x12, 0x0a, 0x0d, 0x49, 0x44, 0x5f, 0x43, 0x32, 0x53,
	0x5f, 0x47, 0x52, 0x4f, 0x57, 0x54, 0x48, 0x10, 0xab, 0x56, 0x12, 0x12, 0x0a, 0x0d, 0x49, 0x44,
	0x5f, 0x53, 0x32, 0x43, 0x5f, 0x47, 0x52, 0x4f, 0x57, 0x54, 0x48, 0x10, 0xac, 0x56, 0x12, 0x19,
	0x0a, 0x14, 0x49, 0x44, 0x5f, 0x43, 0x32, 0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4f, 0x53, 0x45,
	0x5f, 0x54, 0x4f, 0x4f, 0x4c, 0x53, 0x10, 0xb5, 0x56, 0x12, 0x19, 0x0a, 0x14, 0x49, 0x44, 0x5f,
	0x53, 0x32, 0x43, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4f, 0x53, 0x45, 0x5f, 0x54, 0x4f, 0x4f, 0x4c,
	0x53, 0x10, 0xb6, 0x56, 0x12, 0x25, 0x0a, 0x1f, 0x49, 0x44, 0x5f, 0x53, 0x32, 0x43, 0x5f, 0x42,
	0x41, 0x53, 0x45, 0x5f, 0x54, 0x4f, 0x4f, 0x4c, 0x53, 0x5f, 0x48, 0x55, 0x47, 0x45, 0x5f, 0x4d,
	0x53, 0x47, 0x5f, 0x50, 0x41, 0x43, 0x4b, 0x10, 0x9e, 0x8d, 0x06, 0x12, 0x29, 0x0a, 0x23, 0x49,
	0x44, 0x5f, 0x53, 0x32, 0x43, 0x5f, 0x42, 0x41, 0x53, 0x45, 0x5f, 0x54, 0x4f, 0x4f, 0x4c, 0x53,
	0x5f, 0x48, 0x55, 0x47, 0x45, 0x5f, 0x4d, 0x53, 0x47, 0x5f, 0x53, 0x55, 0x42, 0x5f, 0x50, 0x41,
	0x43, 0x4b, 0x10, 0x9f, 0x8d, 0x06, 0x32, 0xf5, 0x03, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x0f, 0x2e, 0x63, 0x73, 0x2e, 0x43, 0x32, 0x53, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x1a, 0x0f, 0x2e, 0x63, 0x73, 0x2e, 0x53, 0x32, 0x43, 0x5f, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x42, 0x6f, 0x72, 0x6e, 0x12, 0x0c, 0x2e, 0x63, 0x73,
	0x2e, 0x43, 0x32, 0x53, 0x5f, 0x42, 0x4f, 0x52, 0x4e, 0x1a, 0x0c, 0x2e, 0x63, 0x73, 0x2e, 0x53,
	0x32, 0x43, 0x5f, 0x42, 0x4f, 0x52, 0x4e, 0x12, 0x22, 0x0a, 0x04, 0x44, 0x65, 0x61, 0x64, 0x12,
	0x0c, 0x2e, 0x63, 0x73, 0x2e, 0x43, 0x32, 0x53, 0x5f, 0x44, 0x45, 0x41, 0x44, 0x1a, 0x0c, 0x2e,
	0x63, 0x73, 0x2e, 0x53, 0x32, 0x43, 0x5f, 0x44, 0x45, 0x41, 0x44, 0x12, 0x22, 0x0a, 0x04, 0x4d,
	0x6f, 0x76, 0x65, 0x12, 0x0c, 0x2e, 0x63, 0x73, 0x2e, 0x43, 0x32, 0x53, 0x5f, 0x4d, 0x4f, 0x56,
	0x45, 0x1a, 0x0c, 0x2e, 0x63, 0x73, 0x2e, 0x53, 0x32, 0x43, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x12,
	0x37, 0x0a, 0x07, 0x43, 0x75, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x12, 0x15, 0x2e, 0x63, 0x73, 0x2e,
	0x43, 0x32, 0x53, 0x5f, 0x43, 0x55, 0x54, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x5f, 0x54, 0x52, 0x45,
	0x45, 0x1a, 0x15, 0x2e, 0x63, 0x73, 0x2e, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x55, 0x54, 0x5f, 0x44,
	0x4f, 0x57, 0x4e, 0x5f, 0x54, 0x52, 0x45, 0x45, 0x12, 0x3f, 0x0a, 0x09, 0x42, 0x65, 0x43, 0x75,
	0x74, 0x44, 0x6f, 0x77, 0x6e, 0x12, 0x18, 0x2e, 0x63, 0x73, 0x2e, 0x43, 0x32, 0x53, 0x5f, 0x42,
	0x45, 0x5f, 0x43, 0x55, 0x54, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x5f, 0x54, 0x52, 0x45, 0x45, 0x1a,
	0x18, 0x2e, 0x63, 0x73, 0x2e, 0x53, 0x32, 0x43, 0x5f, 0x42, 0x45, 0x5f, 0x43, 0x55, 0x54, 0x5f,
	0x44, 0x4f, 0x57, 0x4e, 0x5f, 0x54, 0x52, 0x45, 0x45, 0x12, 0x25, 0x0a, 0x05, 0x53, 0x6c, 0x65,
	0x65, 0x70, 0x12, 0x0d, 0x2e, 0x63, 0x73, 0x2e, 0x43, 0x32, 0x53, 0x5f, 0x53, 0x4c, 0x45, 0x45,
	0x50, 0x1a, 0x0d, 0x2e, 0x63, 0x73, 0x2e, 0x53, 0x32, 0x43, 0x5f, 0x53, 0x4c, 0x45, 0x45, 0x50,
	0x12, 0x1f, 0x0a, 0x03, 0x45, 0x61, 0x74, 0x12, 0x0b, 0x2e, 0x63, 0x73, 0x2e, 0x43, 0x32, 0x53,
	0x5f, 0x45, 0x41, 0x54, 0x1a, 0x0b, 0x2e, 0x63, 0x73, 0x2e, 0x53, 0x32, 0x43, 0x5f, 0x45, 0x41,
	0x54, 0x12, 0x2a, 0x0a, 0x06, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x12, 0x0f, 0x2e, 0x63, 0x73,
	0x2e, 0x43, 0x32, 0x53, 0x5f, 0x50, 0x49, 0x43, 0x4b, 0x5f, 0x55, 0x50, 0x1a, 0x0f, 0x2e, 0x63,
	0x73, 0x2e, 0x53, 0x32, 0x43, 0x5f, 0x50, 0x49, 0x43, 0x4b, 0x5f, 0x55, 0x50, 0x12, 0x26, 0x0a,
	0x04, 0x47, 0x72, 0x6f, 0x77, 0x12, 0x0e, 0x2e, 0x63, 0x73, 0x2e, 0x43, 0x32, 0x53, 0x5f, 0x47,
	0x52, 0x4f, 0x57, 0x54, 0x48, 0x1a, 0x0e, 0x2e, 0x63, 0x73, 0x2e, 0x53, 0x32, 0x43, 0x5f, 0x47,
	0x52, 0x4f, 0x57, 0x54, 0x48, 0x12, 0x37, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65,
	0x12, 0x15, 0x2e, 0x63, 0x73, 0x2e, 0x43, 0x32, 0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4f, 0x53,
	0x45, 0x5f, 0x54, 0x4f, 0x4f, 0x4c, 0x53, 0x1a, 0x15, 0x2e, 0x63, 0x73, 0x2e, 0x53, 0x32, 0x43,
	0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4f, 0x53, 0x45, 0x5f, 0x54, 0x4f, 0x4f, 0x4c, 0x53, 0x42, 0x14,
	0x5a, 0x07, 0x54, 0x65, 0x73, 0x74, 0x2f, 0x63, 0x73, 0xaa, 0x02, 0x08, 0x63, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cs_proto_rawDescOnce sync.Once
	file_cs_proto_rawDescData = file_cs_proto_rawDesc
)

func file_cs_proto_rawDescGZIP() []byte {
	file_cs_proto_rawDescOnce.Do(func() {
		file_cs_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_proto_rawDescData)
	})
	return file_cs_proto_rawDescData
}

var file_cs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cs_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_cs_proto_goTypes = []interface{}{
	(ID)(0),                      // 0: cs.ID
	(*Zero)(nil),                 // 1: cs.Zero
	(*User)(nil),                 // 2: cs.User
	(*OpUser)(nil),               // 3: cs.OpUser
	(*Item)(nil),                 // 4: cs.Item
	(*S2C_OpObject)(nil),         // 5: cs.S2C_OpObject
	(*C2S_GetUser)(nil),          // 6: cs.C2S_GetUser
	(*S2C_GetUser)(nil),          // 7: cs.S2C_GetUser
	(*C2S_BORN)(nil),             // 8: cs.C2S_BORN
	(*S2C_BORN)(nil),             // 9: cs.S2C_BORN
	(*C2S_DEAD)(nil),             // 10: cs.C2S_DEAD
	(*S2C_DEAD)(nil),             // 11: cs.S2C_DEAD
	(*C2S_MOVE)(nil),             // 12: cs.C2S_MOVE
	(*S2C_MOVE)(nil),             // 13: cs.S2C_MOVE
	(*C2S_CUT_DOWN_TREE)(nil),    // 14: cs.C2S_CUT_DOWN_TREE
	(*S2C_CUT_DOWN_TREE)(nil),    // 15: cs.S2C_CUT_DOWN_TREE
	(*C2S_BE_CUT_DOWN_TREE)(nil), // 16: cs.C2S_BE_CUT_DOWN_TREE
	(*S2C_BE_CUT_DOWN_TREE)(nil), // 17: cs.S2C_BE_CUT_DOWN_TREE
	(*C2S_SLEEP)(nil),            // 18: cs.C2S_SLEEP
	(*S2C_SLEEP)(nil),            // 19: cs.S2C_SLEEP
	(*C2S_EAT)(nil),              // 20: cs.C2S_EAT
	(*S2C_EAT)(nil),              // 21: cs.S2C_EAT
	(*C2S_PICK_UP)(nil),          // 22: cs.C2S_PICK_UP
	(*S2C_PICK_UP)(nil),          // 23: cs.S2C_PICK_UP
	(*C2S_GROWTH)(nil),           // 24: cs.C2S_GROWTH
	(*S2C_GROWTH)(nil),           // 25: cs.S2C_GROWTH
	(*C2S_COMPOSE_TOOLS)(nil),    // 26: cs.C2S_COMPOSE_TOOLS
	(*S2C_COMPOSE_TOOLS)(nil),    // 27: cs.S2C_COMPOSE_TOOLS
}
var file_cs_proto_depIdxs = []int32{
	2,  // 0: cs.OpUser.insert:type_name -> cs.User
	2,  // 1: cs.OpUser.update:type_name -> cs.User
	2,  // 2: cs.OpUser.delete:type_name -> cs.User
	3,  // 3: cs.S2C_OpObject.opUser:type_name -> cs.OpUser
	2,  // 4: cs.S2C_GetUser.user:type_name -> cs.User
	2,  // 5: cs.S2C_BORN.user:type_name -> cs.User
	4,  // 6: cs.C2S_PICK_UP.itemList:type_name -> cs.Item
	4,  // 7: cs.S2C_PICK_UP.itemList:type_name -> cs.Item
	4,  // 8: cs.C2S_COMPOSE_TOOLS.needItem:type_name -> cs.Item
	4,  // 9: cs.C2S_COMPOSE_TOOLS.resultItem:type_name -> cs.Item
	4,  // 10: cs.S2C_COMPOSE_TOOLS.needItem:type_name -> cs.Item
	4,  // 11: cs.S2C_COMPOSE_TOOLS.resultItem:type_name -> cs.Item
	6,  // 12: cs.UserService.GetUser:input_type -> cs.C2S_GetUser
	8,  // 13: cs.UserService.Born:input_type -> cs.C2S_BORN
	10, // 14: cs.UserService.Dead:input_type -> cs.C2S_DEAD
	12, // 15: cs.UserService.Move:input_type -> cs.C2S_MOVE
	14, // 16: cs.UserService.CutDown:input_type -> cs.C2S_CUT_DOWN_TREE
	16, // 17: cs.UserService.BeCutDown:input_type -> cs.C2S_BE_CUT_DOWN_TREE
	18, // 18: cs.UserService.Sleep:input_type -> cs.C2S_SLEEP
	20, // 19: cs.UserService.Eat:input_type -> cs.C2S_EAT
	22, // 20: cs.UserService.PickUp:input_type -> cs.C2S_PICK_UP
	24, // 21: cs.UserService.Grow:input_type -> cs.C2S_GROWTH
	26, // 22: cs.UserService.Compose:input_type -> cs.C2S_COMPOSE_TOOLS
	7,  // 23: cs.UserService.GetUser:output_type -> cs.S2C_GetUser
	9,  // 24: cs.UserService.Born:output_type -> cs.S2C_BORN
	11, // 25: cs.UserService.Dead:output_type -> cs.S2C_DEAD
	13, // 26: cs.UserService.Move:output_type -> cs.S2C_MOVE
	15, // 27: cs.UserService.CutDown:output_type -> cs.S2C_CUT_DOWN_TREE
	17, // 28: cs.UserService.BeCutDown:output_type -> cs.S2C_BE_CUT_DOWN_TREE
	19, // 29: cs.UserService.Sleep:output_type -> cs.S2C_SLEEP
	21, // 30: cs.UserService.Eat:output_type -> cs.S2C_EAT
	23, // 31: cs.UserService.PickUp:output_type -> cs.S2C_PICK_UP
	25, // 32: cs.UserService.Grow:output_type -> cs.S2C_GROWTH
	27, // 33: cs.UserService.Compose:output_type -> cs.S2C_COMPOSE_TOOLS
	23, // [23:34] is the sub-list for method output_type
	12, // [12:23] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_cs_proto_init() }
func file_cs_proto_init() {
	if File_cs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Zero); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_OpObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_GetUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_GetUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_BORN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_BORN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_DEAD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_DEAD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_MOVE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_MOVE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_CUT_DOWN_TREE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_CUT_DOWN_TREE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_BE_CUT_DOWN_TREE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_BE_CUT_DOWN_TREE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_SLEEP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_SLEEP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_EAT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_EAT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_PICK_UP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_PICK_UP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_GROWTH); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_GROWTH); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_COMPOSE_TOOLS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_COMPOSE_TOOLS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cs_proto_goTypes,
		DependencyIndexes: file_cs_proto_depIdxs,
		EnumInfos:         file_cs_proto_enumTypes,
		MessageInfos:      file_cs_proto_msgTypes,
	}.Build()
	File_cs_proto = out.File
	file_cs_proto_rawDesc = nil
	file_cs_proto_goTypes = nil
	file_cs_proto_depIdxs = nil
}
