// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/ai_service.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 实体位置信息
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_proto_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// 实体基础信息
type EntityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // TREE, WOODCUTTER
	Position      *Position          `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Attributes    map[string]float32 `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // hp, energy等属性
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityInfo) Reset() {
	*x = EntityInfo{}
	mi := &file_proto_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityInfo) ProtoMessage() {}

func (x *EntityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityInfo.ProtoReflect.Descriptor instead.
func (*EntityInfo) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *EntityInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EntityInfo) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EntityInfo) GetAttributes() map[string]float32 {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// 地图信息
type MapInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*EntityInfo          `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapInfo) Reset() {
	*x = MapInfo{}
	mi := &file_proto_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapInfo) ProtoMessage() {}

func (x *MapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapInfo.ProtoReflect.Descriptor instead.
func (*MapInfo) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *MapInfo) GetEntities() []*EntityInfo {
	if x != nil {
		return x.Entities
	}
	return nil
}

// AI决策请求
type DecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *EntityInfo            `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`                                   // 决策主体
	MapInfo       *MapInfo               `protobuf:"bytes,2,opt,name=map_info,json=mapInfo,proto3" json:"map_info,omitempty"`                // 当前地图信息
	CurrentState  string                 `protobuf:"bytes,3,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"` // 当前状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionRequest) Reset() {
	*x = DecisionRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRequest) ProtoMessage() {}

func (x *DecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRequest.ProtoReflect.Descriptor instead.
func (*DecisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{3}
}

func (x *DecisionRequest) GetActor() *EntityInfo {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *DecisionRequest) GetMapInfo() *MapInfo {
	if x != nil {
		return x.MapInfo
	}
	return nil
}

func (x *DecisionRequest) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

// AI决策响应
type DecisionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActionType     string                 `protobuf:"bytes,1,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`             // MOVE, CHOP, LEARN_SKILL
	TargetId       string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                   // 目标实体ID
	TargetPosition *Position              `protobuf:"bytes,3,opt,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"` // 目标位置
	SubCommands    []string               `protobuf:"bytes,4,rep,name=sub_commands,json=subCommands,proto3" json:"sub_commands,omitempty"`          // 具体的执行指令列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DecisionResponse) Reset() {
	*x = DecisionResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponse) ProtoMessage() {}

func (x *DecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponse.ProtoReflect.Descriptor instead.
func (*DecisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{4}
}

func (x *DecisionResponse) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *DecisionResponse) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *DecisionResponse) GetTargetPosition() *Position {
	if x != nil {
		return x.TargetPosition
	}
	return nil
}

func (x *DecisionResponse) GetSubCommands() []string {
	if x != nil {
		return x.SubCommands
	}
	return nil
}

var File_proto_ai_service_proto protoreflect.FileDescriptor

const file_proto_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x16proto/ai_service.proto\x12\x02ai\"4\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"\xd9\x01\n" +
	"\n" +
	"EntityInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12(\n" +
	"\bposition\x18\x03 \x01(\v2\f.offline_ai.PositionR\bposition\x12>\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2\x1e.offline_ai.EntityInfo.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"5\n" +
	"\aMapInfo\x12*\n" +
	"\bentities\x18\x01 \x03(\v2\x0e.offline_ai.EntityInfoR\bentities\"\x84\x01\n" +
	"\x0fDecisionRequest\x12$\n" +
	"\x05actor\x18\x01 \x01(\v2\x0e.offline_ai.EntityInfoR\x05actor\x12&\n" +
	"\bmap_info\x18\x02 \x01(\v2\v.offline_ai.MapInfoR\amapInfo\x12#\n" +
	"\rcurrent_state\x18\x03 \x01(\tR\fcurrentState\"\xaa\x01\n" +
	"\x10DecisionResponse\x12\x1f\n" +
	"\vaction_type\x18\x01 \x01(\tR\n" +
	"actionType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x125\n" +
	"\x0ftarget_position\x18\x03 \x01(\v2\f.offline_ai.PositionR\x0etargetPosition\x12!\n" +
	"\fsub_commands\x18\x04 \x03(\tR\vsubCommands2E\n" +
	"\tAIService\x128\n" +
	"\vGetDecision\x12\x13.offline_ai.DecisionRequest\x1a\x14.offline_ai.DecisionResponseB!Z\x1fgithub.com/hello-world/proto/aib\x06proto3"

var (
	file_proto_ai_service_proto_rawDescOnce sync.Once
	file_proto_ai_service_proto_rawDescData []byte
)

func file_proto_ai_service_proto_rawDescGZIP() []byte {
	file_proto_ai_service_proto_rawDescOnce.Do(func() {
		file_proto_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_service_proto_rawDesc), len(file_proto_ai_service_proto_rawDesc)))
	})
	return file_proto_ai_service_proto_rawDescData
}

var file_proto_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_ai_service_proto_goTypes = []any{
	(*Position)(nil),         // 0: offline_ai.Position
	(*EntityInfo)(nil),       // 1: offline_ai.EntityInfo
	(*MapInfo)(nil),          // 2: offline_ai.MapInfo
	(*DecisionRequest)(nil),  // 3: offline_ai.DecisionRequest
	(*DecisionResponse)(nil), // 4: offline_ai.DecisionResponse
	nil,                      // 5: offline_ai.EntityInfo.AttributesEntry
}
var file_proto_ai_service_proto_depIdxs = []int32{
	0, // 0: offline_ai.EntityInfo.position:type_name -> offline_ai.Position
	5, // 1: offline_ai.EntityInfo.attributes:type_name -> offline_ai.EntityInfo.AttributesEntry
	1, // 2: offline_ai.MapInfo.entities:type_name -> offline_ai.EntityInfo
	1, // 3: offline_ai.DecisionRequest.actor:type_name -> offline_ai.EntityInfo
	2, // 4: offline_ai.DecisionRequest.map_info:type_name -> offline_ai.MapInfo
	0, // 5: offline_ai.DecisionResponse.target_position:type_name -> offline_ai.Position
	3, // 6: offline_ai.AIService.GetDecision:input_type -> offline_ai.DecisionRequest
	4, // 7: offline_ai.AIService.GetDecision:output_type -> offline_ai.DecisionResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_ai_service_proto_init() }
func file_proto_ai_service_proto_init() {
	if File_proto_ai_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_service_proto_rawDesc), len(file_proto_ai_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_service_proto_goTypes,
		DependencyIndexes: file_proto_ai_service_proto_depIdxs,
		MessageInfos:      file_proto_ai_service_proto_msgTypes,
	}.Build()
	File_proto_ai_service_proto = out.File
	file_proto_ai_service_proto_goTypes = nil
	file_proto_ai_service_proto_depIdxs = nil
}
